version: "3.9"
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    volumes:
      - mgstorage:/data/db
    network_mode: "host"
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: flask
    depends_on:
      - mongo
    network_mode: "host"
  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    container_name: dash
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: dash
    depends_on:
      - flask
    network_mode: "host"
volumes:
  mgstorage:
    external: true

